services:
  api:
    build: .
    container_name: career-coach-api2
    env_file: .env
    ports:
      - "8044:8000"
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:7
    container_name: career-coach-mongo2
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:


